### PR TITLE
Fixes for docker configuration when running on macOS (darwin) Mojave

### LINKED ISSUE #14: Does not work under macOS Mojave
Saving triggers a reload of the internal browser, but it does not trigger a re-built of the HTML. External browsers show the outdated HTML, too. Not even a restart of the container securely triggers a new built.

November 2018 on macOS Mojave

Digging a little deeper. The Sphinx-Server is working, if I start it from the command line like given in its documentation:

`docker run -itd -v "$(pwd)":/web -u $(id -u):$(id -g) -p 8000:8000 --name sphinx-server dldl/sphinx-server`

When I edit the files and save them, the change watcher works and rebuilds the HTML. I can follow this in the console of Kitematik. I can call the changed HTML with any Browser.

```
[I 181124 20:39:37 server:298](B Serving on http://0.0.0.0:8000
[I 181124 20:39:37 handlers:59](B Start watching changes
[I 181124 20:39:37 handlers:61](B Start detecting changes
[I 181124 20:39:47 handlers:132](B Browser Connected: http://127.0.0.1:8000/Architektur.html
+--------- Architektur.rst changed ----------------------------------------------
| Running Sphinx v1.8.2
```

When I start the Server from within the Atom Editor it does not work any longer.  It just does not detect the change. It also comes under the container name: Sphinx-Preview. The only difference I see is in the ports:

```
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                              NAMES
958b2f7614eb        dldl/sphinx-server   "python /opt/sphinx-…"   3 minutes ago       Up 58 seconds       0.0.0.0:8000->8000/tcp, 0.0.0.0:35729->35729/tcp   sphinx-preview

CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                               NAMES
c1fb5d789a70        dldl/sphinx-server   "python /opt/sphinx-…"   5 seconds ago       Up 3 seconds        0.0.0.0:8000->8000/tcp, 35729/tcp   sphinx-server
```

### The Workaround

This brings me to the workaround to start the container from outside as 'sphinx-preview' like so or just start it from within Kitematik.

```
docker run -itd -v "$(pwd)":/web -u $(id -u):$(id -g) -p 8000:8000 --name sphinx-preview dldl/sphinx-server
```

The latency between saving and building is about 10 seconds. This is too slow to be really satisfying and yet it is the best setup for authoring I have seen so far. Drive it forward and we will get better docs in the future.

How about a docker container, that renders Sphinx in high quality with a LaTeX setup to PDF?

### PR DESCRIPTION
**Pull request by hileef**
Potentially (aka works on my macOS Mojave machine) fixes #14

`python-reload`'s file watcher behaves erratically when run in a docker environment when the host is macOS (darwin) Mojave, I believe it may be a bug either in the docker engine itself or in the darwin kernel when handling `//double/slash/posix-n-win32-compatible/paths`, as well as differing configuration.

This patch is based on having run `docker inspect` on the container as launched form the `sphinx-preview` plugin and as launched from the command line.

I have not encountered the problems mentioned in #14 with these patches, however given the erratic nature of the error it is very difficult to test in an automated way.

### CODE REVIEW

File: lib/sphinx-preview.js [hunk 1]
```diff
@@ -3,6 +3,8 @@
 import { CompositeDisposable } from 'atom';
 import Docker from 'dockerode';
 
+const os = require('os');
```
Comment (Coac) [inline lib/sphinx-preview.js]: Maybe use import instead of require to be consistent
```suggestion
import { os } from 'os';
```

File: lib/sphinx-preview.js [hunk 2]
```diff
@@ -3,6 +3,8 @@
 import { CompositeDisposable } from 'atom';
 import Docker from 'dockerode';
```
Comment (Coac) [inline lib/sphinx-preview.js]:
```suggestion
```

**Review by Coac — CHANGES_REQUESTED** [review]
Seems correct, could not test it directly as I am running it on Linux, but still working :)
If you can fix the eslint errors, we can merge

File: lib/sphinx-preview.js (hunk 1 above)
Comment (hileef) [reply lib/sphinx-preview.js]: see [55133fb](https://github.com/dldl/sphinx-preview/pull/16/commits/55133fbc4fe7ed39909540cdf9a0caf85caec077)

File: lib/sphinx-preview.js (hunk 2 above)
Comment (hileef) [reply lib/sphinx-preview.js]: see [55133fb](https://github.com/dldl/sphinx-preview/pull/16/commits/55133fbc4fe7ed39909540cdf9a0caf85caec077)

**Comment by hileef** [comment]
@Coac , could you have a look at the changes I have put in place and tell me if it's okay now ?
Thanks in advance !

**Review by Coac — APPROVED** [review]

**Comment by Coac** [comment]
Thanks!
